- name: PHP のインストール
  yum: name="{{item}}" state=latest
  with_items:
    - php
    - php-mysql

- name: タイムゾーンの設定
  ini_file: >
    dest=/etc/php.ini
    section=Date
    option=date.timezone
    value='"Asia/Tokyo"'

- name: php テストページの作成
  copy: src=phpinfo.php dest=/var/www/html/phpinfo.php

- name: httpサービスの再起動
  service: name=httpd state=restarted enabled=yes